[package]
name = "kudos"
version = "0.1.0"
edition = "2024_07"

[scripts]
test = "snforge test"

[tool.fmt]
sort-module-level-items = true

[dependencies]
starknet = "2.8.5"

[dev-dependencies]
assert_macros = "2.8.5"
snforge_std = "0.33.0"

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy= "avoid"

[default.networks.sepolia.provider]
type = "free"
vendor = "nethermind"

[[target.starknet-contract]]
casm = true
