[package]
name = "kudos"
version = "0.1.0"
edition = "2024_07"

[scripts]
test = "snforge test"

[tool.fmt]
sort-module-level-items = true

[dependencies]
starknet = "2.8.2"
openzeppelin_token = "0.16.0"

[dev-dependencies]
assert_macros = "2.8.2"
snforge_std = "0.30.0"

[[target.starknet-contract]]
