[package]
name = "contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.8.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.30.0" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
