[package]
name = "kudos"
version = "0.1.0"
edition = "2023_01"

[scripts]
test = "snforge test"

[tool.fmt]
sort-module-level-items = true

[dependencies]
starknet = "2.6.3"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.21.0" }

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy= "avoid"

[[target.starknet-contract]]
