name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: asdf-vm/actions/install@v3
            - run: scarb fmt --check
              working-directory: contracts
            - run: go fmt --check
              working-directory: api

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: asdf-vm/actions/install@v3
            - run: scarb test
              working-directory: contracts
