name: Example cairo coverage workflow
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - uses: foundry-rs/setup-snfoundry@v3

      - name: Run tests and generate report
        run: cd contracts/ && snforge test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: .contracts/coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}ENV>
